"""empty message

Revision ID: 0fe199e59282
Revises: 59ce56ffcd9c
Create Date: 2021-09-22 19:05:26.377826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fe199e59282'
down_revision = '59ce56ffcd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlistvideojoins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlistId', sa.Integer(), nullable=True),
    sa.Column('videoId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playlistId'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['videoId'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('PlaylistVideoJoins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PlaylistVideoJoins',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"PlaylistVideoJoins_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('playlistId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('videoId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlistId'], ['playlists.id'], name='PlaylistVideoJoins_playlistId_fkey'),
    sa.ForeignKeyConstraint(['videoId'], ['videos.id'], name='PlaylistVideoJoins_videoId_fkey'),
    sa.PrimaryKeyConstraint('id', name='PlaylistVideoJoins_pkey')
    )
    op.drop_table('playlistvideojoins')
    # ### end Alembic commands ###
